name: remember_medicine
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  email_validator: ^2.1.17
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.6
  firebase_database: ^11.0.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.2
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.3
  firebase_messaging: ^15.0.2
  provider: ^6.1.2
  permission_handler: ^11.3.1
  another_flushbar: ^1.12.30
  flutter_blue_plus: ^1.32.8
  flutter_launcher_icons: ^0.13.1
  flutter_blue: ^0.8.0
  get: ^4.6.6
  ble_controller: ^0.0.43
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assest/image/
