// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChJdO3zMojqswZvzCJru3ugHEKne-pihM',
    appId: '1:1046634708335:web:1e17d5157755274f6f3c9a',
    messagingSenderId: '1046634708335',
    projectId: 'medicine-db-58c31',
    authDomain: 'medicine-db-58c31.firebaseapp.com',
    storageBucket: 'medicine-db-58c31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0wwE-kP8P4ILUVny9Kt8yGp-FGZZnC94',
    appId: '1:1046634708335:android:93f9a1af73f86baa6f3c9a',
    messagingSenderId: '1046634708335',
    projectId: 'medicine-db-58c31',
    storageBucket: 'medicine-db-58c31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSQtwfNsdPxOqc_2NJNvjWWZ9ekIhPE0U',
    appId: '1:1046634708335:ios:e2799d726fef1cb06f3c9a',
    messagingSenderId: '1046634708335',
    projectId: 'medicine-db-58c31',
    storageBucket: 'medicine-db-58c31.appspot.com',
    iosBundleId: 'com.example.rememberMedicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSQtwfNsdPxOqc_2NJNvjWWZ9ekIhPE0U',
    appId: '1:1046634708335:ios:e2799d726fef1cb06f3c9a',
    messagingSenderId: '1046634708335',
    projectId: 'medicine-db-58c31',
    storageBucket: 'medicine-db-58c31.appspot.com',
    iosBundleId: 'com.example.rememberMedicine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChJdO3zMojqswZvzCJru3ugHEKne-pihM',
    appId: '1:1046634708335:web:bc99606b7746c5316f3c9a',
    messagingSenderId: '1046634708335',
    projectId: 'medicine-db-58c31',
    authDomain: 'medicine-db-58c31.firebaseapp.com',
    storageBucket: 'medicine-db-58c31.appspot.com',
  );
}
