// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7kMJRSDEdBPA9n6wyUDSYIBg6EtDzcYA',
    appId: '1:567544252680:web:e4caf57b40147594ca84bd',
    messagingSenderId: '567544252680',
    projectId: 'medicine-28633',
    authDomain: 'medicine-28633.firebaseapp.com',
    storageBucket: 'medicine-28633.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyxIPmaByJVggQZzgApwhvRolAkMfnnow',
    appId: '1:567544252680:android:90273d80d3f45ab0ca84bd',
    messagingSenderId: '567544252680',
    projectId: 'medicine-28633',
    storageBucket: 'medicine-28633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSNOeKm2Ik02p39lXJ5Ehks5SASCzs5a8',
    appId: '1:567544252680:ios:fe059b7249bb9dfcca84bd',
    messagingSenderId: '567544252680',
    projectId: 'medicine-28633',
    storageBucket: 'medicine-28633.appspot.com',
    iosBundleId: 'com.example.rememberMedicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSNOeKm2Ik02p39lXJ5Ehks5SASCzs5a8',
    appId: '1:567544252680:ios:fe059b7249bb9dfcca84bd',
    messagingSenderId: '567544252680',
    projectId: 'medicine-28633',
    storageBucket: 'medicine-28633.appspot.com',
    iosBundleId: 'com.example.rememberMedicine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7kMJRSDEdBPA9n6wyUDSYIBg6EtDzcYA',
    appId: '1:567544252680:web:e635dbafde14c8fdca84bd',
    messagingSenderId: '567544252680',
    projectId: 'medicine-28633',
    authDomain: 'medicine-28633.firebaseapp.com',
    storageBucket: 'medicine-28633.appspot.com',
  );
}
